image: ubuntu:latest

variables:
  versionBuilder: "2.0"
  arch: "--all"
  addon: "cloudflare-dyndns"

stages:
  - build

.build:
  stage: build
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - docker pull homeassistant/amd64-builder:${versionBuilder}
    - docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:${versionBuilder} \
        --addon ${arch} -t /data/${addon} \
        --docker-hub ${DOCKER_USERNAME} --docker-hub-check

build_clouflare-dyndns:
  extends: .build
  variables:
    versionBuilder: "2.0"
    arch: "--all"
    addon: "cloudflare-dyndns"
  stage: build
  only:
    changes:
      - cloudflare-dyndns/*
